version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgvector-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase